name: CodeDroid X CI Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Zde je ten trik! Použijeme ofiko GitHub akci, která 
    # natvrdo nainstaluje Gradle 8.2, takže verze 9.7 nás už nebude otravovat.
    - name: Setup Gradle 8.2
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.2

    # Teď když máme 100% zaručený Gradle 8.2, bezpečně vygenerujeme wrapper
    - name: Vygeneruj Wrapper pro jistotu
      run: gradle wrapper --gradle-version 8.2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CodeDroidX-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
